modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="supreme_armour"
version="0.3.0"
displayName="Supreme Armour"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Herofahad777, MCreator"
description='''Add a varity of 3D armors to the game'''

[[dependencies.supreme_armour]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




